enabled: true
default-multiplier: 10

custom-multipliers:
  IRON_INGOT: 10
  DIAMOND: 10
  STICK: 10




  # Нестакаемые предметы
  WOODEN_SWORD: 1
  STONE_SWORD: 1
  IRON_SWORD: 1
  GOLDEN_SWORD: 1
  DIAMOND_SWORD: 1
  NETHERITE_SWORD: 1

  WOODEN_PICKAXE: 1
  STONE_PICKAXE: 1
  IRON_PICKAXE: 1
  GOLDEN_PICKAXE: 1
  DIAMOND_PICKAXE: 1
  NETHERITE_PICKAXE: 1

  WOODEN_AXE: 1
  STONE_AXE: 1
  IRON_AXE: 1
  GOLDEN_AXE: 1
  DIAMOND_AXE: 1
  NETHERITE_AXE: 1

  WOODEN_SHOVEL: 1
  STONE_SHOVEL: 1
  IRON_SHOVEL: 1
  GOLDEN_SHOVEL: 1
  DIAMOND_SHOVEL: 1
  NETHERITE_SHOVEL: 1

  WOODEN_HOE: 1
  STONE_HOE: 1
  IRON_HOE: 1
  GOLDEN_HOE: 1
  DIAMOND_HOE: 1
  NETHERITE_HOE: 1

  SHIELD: 1
  FLINT_AND_STEEL: 1
  SHEARS: 1
  FISHING_ROD: 1
  CARROT_ON_A_STICK: 1
  WARPED_FUNGUS_ON_A_STICK: 1
  CROSSBOW: 1
  TRIDENT: 1
  SPYGLASS: 1
  BRUSH: 1

  TURTLE_HELMET: 1
  LEATHER_HELMET: 1
  LEATHER_CHESTPLATE: 1
  LEATHER_LEGGINGS: 1
  LEATHER_BOOTS: 1
  CHAINMAIL_HELMET: 1
  CHAINMAIL_CHESTPLATE: 1
  CHAINMAIL_LEGGINGS: 1
  CHAINMAIL_BOOTS: 1
  IRON_HELMET: 1
  IRON_CHESTPLATE: 1
  IRON_LEGGINGS: 1
  IRON_BOOTS: 1
  GOLDEN_HELMET: 1
  GOLDEN_CHESTPLATE: 1
  GOLDEN_LEGGINGS: 1
  GOLDEN_BOOTS: 1
  DIAMOND_HELMET: 1
  DIAMOND_CHESTPLATE: 1
  DIAMOND_LEGGINGS: 1
  DIAMOND_BOOTS: 1
  NETHERITE_HELMET: 1
  NETHERITE_CHESTPLATE: 1
  NETHERITE_LEGGINGS: 1
  NETHERITE_BOOTS: 1

  BUCKET: 1
  MINECART: 1
  CHEST_MINECART: 1
  FURNACE_MINECART: 1
  HOPPER_MINECART: 1
  TNT_MINECART: 1
  COMMAND_BLOCK_MINECART: 1
  BOAT: 1
  OAK_BOAT: 1
  SPRUCE_BOAT: 1
  BIRCH_BOAT: 1
  JUNGLE_BOAT: 1
  ACACIA_BOAT: 1
  DARK_OAK_BOAT: 1
  MANGROVE_BOAT: 1
  BAMBOO_RAFT: 1


